-- INCLUDE ACTUAL EXECUTION PLAN

USE JATH
GO

DECLARE Customers_Cursor CURSOR FOR
	SELECT [CUSTOMER_ID],[EMAIL_ADDRESS]
	FROM [JATH].[CUSTOMERS]
OPEN Customers_Cursor;
FETCH NEXT FROM Customers_Cursor;
WHILE @@FETCH_STATUS =  0
	BEGIN
		FETCH NEXT FROM Customers_Cursor
	END;
CLOSE Customers_Cursor;
DEALLOCATE Customers_Cursor;
GO